<?php
// $Id: xmlsitemap_menu.install,v 1.1.4.14.2.7 2009/05/01 20:17:15 davereid Exp $

/**
 * @file
 * Install and uninstall schema and functions for the xmlsitemap_menu module.
 */

/**
 * Implementation of hook_uninstall().
 */
function xmlsitemap_menu_uninstall() {
  // Remove variables.
  drupal_load('module', 'xmlsitemap_menu');
  $variables = array_keys(xmlsitemap_menu_variables());
  foreach ($variables as $variable) {
    variable_del($variable);
  }
}
